import React, { useState } from 'react'
// @ts-ignore
import queryString from 'query-string';
import { HeroBySuperhero } from '../../components/helpers/HeroBySuperhero';
import { HeroeFound } from './HeroeFound';

export interface HeroeInterface {
    id:               string;
    superhero:        string;
    publisher:        string;
    alter_ego:        string;
    first_appearance: string;
    characters:       string;
}

export const SearchScreen = ({history, location}:any) => {

    // const [searchText, setSearchText] = useState('');
    // const [heroesFound, setHeroesFound] = useState<HeroeInterface[]>([]); 


    // console.log(queryString.parse(location.search));
    const {q=''} = queryString.parse(location.search)
    const [formulario, setFormulario] = useState({searchText: q})
    const {searchText} = formulario;
    
    
    const handleChange = (e:any) => {
        console.log(formulario);
        setFormulario({
            ...formulario, searchText:e.target.value
        });
        
        // console.log(e.target.value);
        // setSearchText(e.target.value);
    }
    
    const handleSubmit = (e:any) => {
        e.preventDefault();
        history.push(`?q=${searchText}`)
    }
    
    const heroesFound = HeroBySuperhero(q);


    return (
        <div>
              <h2>Search Scren</h2>
              <hr />
              <div className="search-items">
                <div className="search-items-1">
                    <h3>Busca tu heroe favorito</h3>
                    <form onSubmit={handleSubmit} >
                        <input type="text" onChange={handleChange} value={searchText} />
                        <button>Buscar</button>
                    </form>
                </div>
                <div className="search-items-2">
                    <h3>Resultado</h3>
                    {
                        (heroesFound.length) ? 
                        (
                        heroesFound.map(heroe => <HeroeFound {...heroe} /> ))
                        :
                        <p>Heroe no encontrado</p>
                        //   {JSON.stringify(heroesFound, null,)}
                    }
                </div>
               </div>

        </div>
    )
}

// Generated by https://quicktype.io



